export const ADD_MOVIE_TO_WATCLIST = "ADD_MOVIE_TO_WATCLIST";
export const REMOVE_MOVIE_FROM_WATCHLIST = "REMOVE_MOVIE_FROM_WATCHLIST";
export const MOVE_TO_WATCHLIST = "MOVE_TO_WATCHLIST";
export const ADD_MOVIE_TO_WATCHED = "ADD_MOVIE_TO_WATCHED";
export const REMOVE_MMOVIE_FROM_WATCHED = "REMOVE_MMOVIE_FROM_WATCHED";
